solver_names = [
    'Brandon', 'Debra', 'Edward', 'Heather', 'Melissa', 'Stephen',
    'Jeffrey', 'Elijah', 'Joan', 'Judy', 'Martha', 'Kevin', 'Kenneth',
    'Virginia', 'Sean', 'Mary', 'John', 'Jacqueline', 'Patricia', 'Aaron',
    'Paul', 'Alexander', 'Julie', 'Olivia', 'Willie', 'Philip', 'Joyce',
    'Jason', 'Adam', 'Jesse', 'Margaret', 'Walter', 'Brittany', 'Sophia',
    'Eugene', 'Betty', 'Randy', 'Peter', 'Benjamin', 'Ethan', 'Jeremy',
    'Carl', 'Marie', 'Amy', 'Theresa', 'Christopher', 'Kyle', 'Hannah',
    'Wayne', 'Kathleen', 'Michelle', 'Isabella', 'Noah', 'Nicole',
    'Stephanie', 'Alan', 'Jack', 'Tyler', 'Evelyn', 'Harold', 'Bruce',
    'Vincent', 'Beverly', 'Gabriel', 'Brian', 'Natalie', 'Ronald', 'James',
    'Henry', 'Zachary', 'Sara', 'Amber', 'Thomas', 'Gregory', 'Larry',
    'Emily', 'Terry', 'Daniel', 'Amanda', 'Gloria', 'Julia', 'Ruth',
    'Lisa', 'Timothy', 'Roger', 'Samuel', 'Cynthia', 'Eric', 'Nathan',
    'Scott', 'Kimberly', 'George', 'Frances', 'Teresa', 'Ashley', 'Kayla',
    'Dennis', 'Laura', 'Alexis', 'Karen', 'Kathryn', 'Christian',
    'Matthew', 'Linda', 'Angela', 'David', 'Rebecca', 'Christine',
    'Carolyn', 'Shirley', 'Justin', 'Samantha', 'Dylan', 'Cheryl', 'Helen',
    'Austin', 'Danielle', 'Maria', 'Elizabeth', 'Jean', 'Keith', 'Mark',
    'Billy', 'Richard', 'Charles', 'Christina', 'Megan', 'Douglas',
    'Louis', 'Nancy', 'Jerry', 'Anna', 'Jessica', 'Sarah', 'Doris',
    'Raymond', 'Rose', 'Grace', 'Andrew', 'Denise', 'Judith', 'Lauren',
    'Arthur', 'Joshua', 'Juan', 'Patrick', 'Diana', 'Charlotte',
    'Nicholas', 'Jennifer', 'Jacob', 'Anthony', 'Carol', 'Sandra',
    'Steven', 'Andrea', 'Bryan', 'Gerald', 'Catherine', 'Susan', 'Deborah',
    'Brenda', 'Abigail', 'Kelly', 'Michael', 'Lawrence', 'Alice', 'Joe',
    'Gary', 'Dorothy', 'Victoria', 'Johnny', 'Donna', 'Ralph', 'Bobby',
    'William', 'Jonathan', 'Janice', 'Jordan', 'Roy', 'Robert', 'Donald',
    'Jose', 'Frank', 'Russell', 'Barbara', 'Pamela', 'Janet', 'Ryan',
    'Diane', 'Ann', 'Sharon', 'Katherine', 'Joseph', 'Marilyn', 'Emma',
    'Madison', 'Albert', 'Logan', 'Rachel'
]
